# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GymWorkout' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GymWorkout

  pod 'Google-Mobile-Ads-SDK'
  pod 'LinearProgressBar'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

end
